version: 2

jobs:
  checkout:
  build:
  deploy-master:
  deploy-dev:
   
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - checkout
      - deploy-dev:
          type: approval
          requires:
            - checkout
          filters:
            branches:
              ignore:
                - master
                - /hotfix-.*/
